

const deleteInvoice = async (req: any) => {
    try {
        console.log(req)
    } catch (error: any) {
    }

}

export { deleteInvoice }